[package]
name = "github-suggestion-cli"
version = "0.0.1"
edition = "2018"

[dependencies]
getopts = "0.2.21"
git2 = "0.13.8"
regex = "1.3.9"
thiserror = "1.0.20"
url = "2.1.1"

github-suggestion = { path = "github-suggestion" }

[workspace]
members = [
	"github-suggestion",
]
