[package]
name = "git-suggested-patch"
version = "0.0.1"
edition = "2018"

[dependencies]
git2 = "0.13.8"
github-rs = "0.7.0"
regex = "1.3.9"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"
thiserror = "1.0.20"
unidiff = "0.3.3"
