[package]
name = "git-suggestion"
version = "0.1.0"
edition = "2018"

[dependencies]
exitcode = "1.1.2"
getopts = "0.2.21"
git2 = "0.13.8"
regex = "1.3.9"
thiserror = "1.0.20"
url = "2.1.1"

github-suggestion = { path = "github-suggestion" }

[workspace]
members = [
	"github-suggestion",
]
